name       : xfce4-terminal
version    : 1.0.4
release    : 1
source     :
    - https://archive.xfce.org/src/apps/xfce4-terminal/1.0/xfce4-terminal-1.0.4.tar.bz2 : 78e55957af7c6fc1f283e90be33988661593a4da98383da1b0b54fdf6554baf4
license    : GPL-2.0-or-later # CHECK ME
component  : desktop.xfce
summary    : Xfce Terminal Emulator.
description: |
    Xfce Terminal Emulator.
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(vte-2.91)
setup      : |
    %configure --disable-debug --libexecdir=/usr/lib64/xfce4
build      : |
    %make
install    : |
    %make_install
